model: "class"
Classifier:
    vocab_size: 21
    model_type: "ResPreAct"
    n_layers: 9
    max_length: 512
    filters: [64, 64, 64, 128, 128, 128, 256, 256, 256]
    kernels: [3, 3, 3, 3, 3, 3, 3, 3, 3]
    dilations: [1, 1, 1, 1, 1, 1, 1, 1, 1]
    strides: [1, 2, 2, 1, 2, 2, 1, 1, 2]
    l1: 0.0
    l2: 0.0
    rate: 0.2
    use_attention: True
    attention_loc: 5
    use_global_pos: False
    temporal_encode: 21
    learning_rate: 0.0001
    batch_size: 64
    epochs: 300
    file: "../weights/classifier11.h5"
Data:
    max_length: 512
    max_samples: 4000000
    base_dir: '/data/RECORDS'
    file_in: '2_22_19.tfrecord'
    file_out: ["22_42_1.tfrecord", "42_62_13.tfrecord", "62_82_34.tfrecord", "82_103_105.tfrecord"]
    shards: 100


