Classifier:
    vocab_size: 21
    n_layers: 6
    max_length: 512
    filters: [64, 64, 64, 128, 128, 128, 256, 256, 256]
    kernels: [6, 6, 6, 4, 4, 4, 4, 4, 4]
    dilations: [1, 1, 1, 1, 1, 1, 1, 1, 1]
    strides: [1, 2, 2, 1, 2, 2, 1, 1, 2]
    l1: 0.0
    l2: 0.0
    rate: 0.2
    use_attention: True
    attention_loc: 5
    use_global_pos: False
    temporal_encode: 21
    learning_rate: 0.0001
    batch_size: 32
    epochs: 300
    file: "../weights/classifier1"
Data:
    max_length: 512
    max_samples: 400000
    dir: '../data/OGT_Classes'
    names_reg: ['ogt_all.fasta']


